### PR TITLE
Update 2015-05-10-Too-busy-right-now.md

### PR DESCRIPTION
**Pull request by Rubenoo**
Gramma and spelling check. Better english

Hey @tux-mind i know that i can't do much because i don't have any programming skills. but i found some wrong gramma on your website so i made it better. I really love your work and keep doing this <3

### CODE REVIEW

**Comment by tux-mind** [comment]
thanks a lot, any help is appreciated :blush:

**Comment by Rubenoo** [comment]
Ow @tux-mind  I just saw another spelling error, can you change the sentence :
-Personally I thought I was a good Object-Oriented programmer. But I was wrong.
To : 
-Personally I thought that I was a good Object-Oriented programmer. But I was wrong.
I will make a merge request anyway. I m sorry that I didn't saw that the first time. Well thank you for your time

**Comment by DominikTV** [comment]
@Rubenoo Don't worry, I changed it, thank you :wink:

**Comment by Rubenoo** [comment]
Yes thank you mate, but when I was correcting this I saw some more spelling wrongs so I've made a pull request for those and thank you @dominikTV for replying so fast and I love the site layout that you've made.

**Pull request merged**
