### PR TITLE
General Updates

### PR DESCRIPTION
**Pull request by AndreaCioccarelli**

### CODE REVIEW

**Comment by DeveloppSoft** [comment]
@AndreaCioccarelli thanks!
I just do not understand why you changed the theme color?

**Comment by AndreaCioccarelli** [comment]
In another pull request, I've introduced the indigo theme color for chrome. cSploit website uses a blue colour but it's not indigo. I've extracted the color and set it as theme-color, so Android users can have an unified and full material-design User Interfacr

**Comment by DeveloppSoft** [comment]
OK, thanks

**Comment by AndreaCioccarelli** [comment]
It's very cool, now site have 2 colors instead of 3
screenshot_20170121-132436

**Comment by DeveloppSoft** [comment]
Yeah, you did a great job :smile:

**Pull request merged**
