### PR TITLE
Update Framework & Push Footer down to bottom

### PR DESCRIPTION
**Pull request by DominikTV**
Updated Framework to 0.97.5 and adding main-tag to push down footer to the bottom.

**BUT:**
Can you add a custom "style.css" file and include it? I don't know how that works here :smile: 
Example: http://dev.dominiktv.net/csploit/ -> Right-click -> View source and in order like line 9 - 12 *(include style.css at last)*

In the style.css - file, please add

```
body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }
  main {
    flex: 1 0 auto;
  }
```

### CODE REVIEW

**Comment by DominikTV** [comment]
Maby also update the donation-page: https://pledgie.com/campaigns/30393 :)

**Comment by tux-mind** [comment]
pledgie should be already in the donation page, isn't it ?

thank you for your great help :blush:

**Comment by DominikTV** [comment]
Nö Problem :)

No, I mean the pledgie page has way more text and information in the page, maby you can update the text on the csploit Website too ;)

**Comment by tux-mind** [comment]
done in 8d3b4b8 :wink: 

thank you again :grin:

**Comment by DominikTV** [comment]
Perfect :)

**Pull request merged**
